azure:
  tenant_id: "ADD"
  client_id: "ADD"
  client_secret: "ADD"
database:
  path: "./../../"
serviceDefinitions:
  path: "../../config/detectionRules"
scan:
  interval: 30m # Interval to scan new message  m = minutes, h = hours
graph:
  api_management_url: "https://reports.office365.com/ecp/reportingwebservice/reporting.svc/MessageTrace" # Full API endpoint without version